[tool.black]
exclude = '/(\.eggs|\.git|\.mypy_cache|\.venv.*|venv*|_build|build|dist|migrations*)/'
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
mypy_path = "."
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = false
exclude = "venv"